
version: 1.0.{build}
clone_folder: c:\SqlObjectsDiff
image: Visual Studio 2017

before_build:
  - nuget restore SqlServerDiff.sln
  - ps: >- [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.Smo") | Out-Null
  [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.SmoExtended") | Out-Null
  [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.ConnectionInfo") | Out-Null
  [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.ExecProcTask") | Out-Null
  [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.Management.CollectorEnum") | Out-Null
  [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.Management.RegisteredServers") | Out-Null

  [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.Management.SqlParser") | Out-Null
  [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.Management.SystemMetadataProvider") | Out-Null
  [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.Management.Utility") | Out-Null
  [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.SqlEnum") | Out-Null
  [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.SqlWmiManagement") | Out-Null
  [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.Management.RegisteredServers") | Out-Null

build:
  project: SqlServerDiff.sln
  parallel: true
  verbosity: minimal
